compil: main.cpp Connection.cpp Connection.hpp err.cpp err.hpp IA1_0/IA.cpp IA1_0/IA.hpp
	g++ -g -o out main.cpp Connection.cpp err.cpp IA1_0/IA.cpp -lcontest -std=c++11

git:
	git pull && git add *

all: compil git
